language: R
cache: packages
sudo: false
warnings_are_errors: false

r:
- release
- devel

os:
- linux
- osx

bioc_packages:
- multtest
- GEOquery

r_packages:
- reshape2
- GSA
- gtools
- cluster
- splines
- stats
- graphics
- grDevices
- utils
- lme4
- gtable
- scales
- tibble
- lazyeval
- foreach
- doParallel
- tcgsaseq
- knitr
- rmarkdown
- viridisLite
- cowplot

r_github_packages:
- r-lib/scales
- tidyverse/ggplot2
- tidyverse/stringr

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--as-cran --no-build-vignettes --no-manual --timings"

env:
  global:
  - _R_CHECK_TIMINGS_="0"
